name: clevertap_flutter
description: Clevertap Flutter plugin to send Clevertap events to Android/iOS
version: 0.0.5
authors:
  - Pooja Bhaumik <pbhaumik26@gmail.com>
  - Raja Earla <earla.raja@gmail.com>
  - Nitish Sahani <nitishssahani@gmail.com>
homepage: https://github.com/bounceshare/clevertap_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.bounceshare.clevertap_flutter
    pluginClass: ClevertapFlutterPlugin

